# ---
# ems_section: "12-gui-setup-wizard"
# ems_subsection: "manifest"
# ems_type: "config"
# ems_scope: "build"
# ems_description: "Cargo manifest for the UI service binary."
# ems_version: "v0.0.0-prealpha"
# ems_owner: "tbd"
# ---
[package]
name = "r-ems-ui"
version = "0.1.0"
edition = "2021"
description = "Terminal UI for exploring R-EMS log files"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
crossterm = { workspace = true }
ratatui = { workspace = true }
chrono = { workspace = true }