# ---
# ems_section: "10-deployment-ci-cd-enhancements"
# ems_subsection: "compose-dev"
# ems_type: "config"
# ems_scope: "infrastructure"
# ems_description: "Developer docker-compose stack for local validation."
# ems_version: "v0.0.0-prealpha"
# ems_owner: "tbd"
# ---
version: "3.9"

services:
  r-emsd:
    container_name: r-emsd-dev
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        APP_VERSION: "dev"
    environment:
      R_EMS_LOG: debug
      R_EMS_CONFIG_SOURCE: /opt/r-ems/configs/docker.dev.toml
      R_EMS_CONFIG_PATH: /data/config/config.toml
    volumes:
      - type: bind
        source: ../configs
        target: /opt/r-ems/configs
      - type: bind
        source: ../ui/setup-wizard/public
        target: /opt/r-ems/ui/setup-wizard
      - type: volume
        source: rems_dev_data
        target: /data
    ports:
      - "8080:8080"
      - "9898:9898"
    restart: unless-stopped

volumes:
  rems_dev_data:
    name: r-ems-dev-data