# ---
# ems_section: "10-deployment-ci-cd-enhancements"
# ems_subsection: "compose-prod"
# ems_type: "config"
# ems_scope: "infrastructure"
# ems_description: "Production docker-compose stack for resilient deployments."
# ems_version: "v0.0.0-prealpha"
# ems_owner: "tbd"
# ---
version: "3.9"

services:
  r-emsd:
    image: ghcr.io/ocean-batteries/r-ems:${R_EMS_VERSION:-latest}
    environment:
      R_EMS_LOG: ${R_EMS_LOG_LEVEL:-info}
      R_EMS_CONFIG_SOURCE: ${R_EMS_CONFIG_SOURCE:-/opt/r-ems/configs/docker.default.toml}
      R_EMS_CONFIG_PATH: ${R_EMS_CONFIG_DIR:-/etc/r-ems}/config.toml
      R_EMS_API_LISTEN: 0.0.0.0:8080
      R_EMS_METRICS_LISTEN: 0.0.0.0:9898
    volumes:
      - type: bind
        source: ${R_EMS_CONFIG_DIR:-/etc/r-ems}
        target: /data/config
      - type: bind
        source: ${R_EMS_LOG_DIR:-/var/lib/r-ems/logs}
        target: /data/logs
      - type: bind
        source: ${R_EMS_SNAPSHOT_DIR:-/var/lib/r-ems/snapshots}
        target: /data/snapshots
    ports:
      - "8080:8080"
      - "9898:9898"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/api/status"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

volumes: {}