# Schemas crate manifest.
#
# This crate bundles the generated Rust types for protobuf definitions used
# throughout the R-EMS Core services. It is compiled as a library so other
# crates can depend on a single source of truth.
[package]
name = "r-ems-schemas"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
prost.workspace = true
prost-types.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tonic.workspace = true

[build-dependencies]
tonic-build.workspace = true
prost-build = "0.12"

[lib]
# Expose the crate as a traditional Rust library.
path = "src/lib.rs"
