# ---
# ems_section: "07-resilience"
# ems_subsection: "03-chaos"
# ems_type: "config"
# ems_scope: "core"
# ems_description: "Sample chaos scenario used during development soak tests."
# ems_version: "v0.1.0"
# ems_owner: "tbd"
# reference: docs/VERSIONING.md
# ---

seed = 1337
jitter_ms = 250

[[actions]]
type = "kill_controller"
grid = "demo-grid"
controller = "primary"
delay_sec = 5

[[actions]]
type = "network_partition"
grid = "demo-grid"
duration_sec = 20
delay_sec = 15

[[actions]]
type = "drop_messages"
grid = "demo-grid"
percentage = 30
duration_sec = 10
delay_sec = 5

[[actions]]
type = "corrupt_snapshot"
grid = "demo-grid"
controller = "secondary"
delay_sec = 25
