mode = "production"

[logging]
directory = "/var/log/r-ems"
format = "structured-json"
file_prefix = "r-emsd"

[license]
path = "/etc/r-ems/license.key"
allow_bypass = false

[update]
feed_path = "configs/update_feed.json"
allow_apply_in_dev = false
poll_interval = 1800

[simulation]
enable_randomized_inputs = false
scenario_files = []
random_seed = 1

[grids.main-grid]
description = "Utility feed and campus distribution"

[grids.main-grid.snapshot]
directory = "/var/lib/r-ems/snapshots/main"
retain_last = 20
auto_replay = true
interval = 60

[grids.main-grid.controllers.primary]
role = "primary"
heartbeat_interval = 1
watchdog_timeout = 3
failover_order = 0
sensor_inputs = ["modbus://plc-a/bus0", "iec61850://substation-1"]

[grids.main-grid.controllers.secondary]
role = "secondary"
heartbeat_interval = 1
watchdog_timeout = 3
failover_order = 1
sensor_inputs = ["modbus://plc-b/bus0", "iec61850://substation-1"]

[grids.microgrid]
description = "Solar + storage microgrid"

[grids.microgrid.snapshot]
directory = "/var/lib/r-ems/snapshots/micro"
retain_last = 15
auto_replay = true
interval = 120

[grids.microgrid.controllers.primary]
role = "primary"
heartbeat_interval = 2
watchdog_timeout = 5
failover_order = 0
sensor_inputs = ["mqtt://telemetry/solar", "mqtt://telemetry/storage"]

[grids.microgrid.controllers.follower]
role = "follower"
heartbeat_interval = 5
watchdog_timeout = 10
failover_order = 2
sensor_inputs = ["mqtt://telemetry/storage"]
