# Simulation configuration
enabled = true
tick_ms = 1000
# telemetry update interval in ms
duration_s = 3600
# total duration of simulation
noise_level = 0.02
# relative random noise
scenario = "default"
# load profile type
