# ---
# ems_section: "02-messaging"
# ems_subsection: "03-transports"
# ems_type: "config"
# ems_scope: "core"
# ems_description: "Development messaging configuration enabling local transports."
# ems_version: "v0.1.0"
# ems_owner: "tbd"
# reference: docs/VERSIONING.md
# ---

# Enable the in-memory transport for single-process testing.
in_memory_enabled = true

# Uncomment to expose the TCP transport once implemented.
# tcp_listen = "127.0.0.1:5005"

# Uncomment to expose the WebSocket transport once implemented.
# websocket_listen = "127.0.0.1:5006"
