mode = "simulation"

[logging]
directory = "/data/logs"
format = "structured-json"
file_prefix = "rpi"

[license]
path = "/data/config/license.key"
allow_bypass = true

[update]
feed_path = "configs/update_feed.json"
allow_apply_in_dev = true
poll_interval = 900

[simulation]
enable_randomized_inputs = true
random_seed = 8675309
scenario_files = ["configs/scenarios/rpi_startup.json"]
replay_speedup = 4.0

[grids.edge-lab]
description = "Balena-connected Raspberry Pi test bench"

[grids.edge-lab.snapshot]
directory = "/data/snapshots/edge"
retain_last = 8
auto_replay = true
interval = 20

[grids.edge-lab.controllers.primary]
role = "primary"
heartbeat_interval = 1
watchdog_timeout = 3
failover_order = 0
sensor_inputs = ["gpio://adc0", "spi://mcp3008/ch0"]

[grids.edge-lab.controllers.hybrid]
role = "secondary"
heartbeat_interval = 1
watchdog_timeout = 3
failover_order = 1
sensor_inputs = ["synthetic://telemetry/voltage", "gpio://adc1"]
