# ---
# ems_section: "06-security"
# ems_subsection: "04-crypto"
# ems_type: "config"
# ems_scope: "core"
# ems_description: "Production security configuration enforcing strict compliance and external TLS assets."
# ems_version: "v0.1.0"
# ems_owner: "tbd"
# reference: docs/VERSIONING.md
# ---

[tls]
cert_path = "secrets/tls/fullchain.pem"
key_path = "secrets/tls/privkey.pem"
allow_self_signed = false

[compliance]
mode = "strict"

[identity]
require_hardware_tokens = true

